### ISSUE TITLE
Feature: add inline unit conversion

### ISSUE THREAD

**Issue by NicoBrown** [NeVeSpl/RevitDBExplorer#1]
Could a column be added to convert the Revit units into whatever the model is in for readability?

![image](https://user-images.githubusercontent.com/69271605/180957063-786f8931-2190-476f-a6da-70a4b093322d.png)

Happy to do it and open a pull request if you think its a good idea?

**Comment by NeVeSpl** [comment]
What would you say about placing that information in a tooltip?

![image](https://user-images.githubusercontent.com/11632757/180986785-f4705233-546f-4e39-8729-e8eec3de4b61.png)

That already is implemented, but there is a bug here:
https://github.com/NeVeSpl/RevitDBExplorer/blob/86acb0ba5d84e8b71b910f5d8bebc0853672cc87/sources/WPF/Converters/FeetToMetersConverter.cs#L16

should be `typeof(double).GetCSharpName()` instead `"Double"`

PR welcome to fix that, or/and expand the tooltip with more unit conversions.

**Comment by NicoBrown** [comment]
I'll take a look at it now and possibly add some more conversions.

If its alright, can I start a Contributions.md at the same time?

**Comment by NeVeSpl** [comment]
sure, you can do every not time-consuming change you want without asking, we will be thinking about its fate during PR review.
