### ISSUE TITLE
Lamda Expresstion not work with Rider

### ISSUE THREAD

**Issue by chuongmep** [NeVeSpl/RevitDBExplorer#10]
Hi @NeVeSpl , do you have any change for 'System.Linq.Expressions.LambdaExpression" for can use in [Rider ](https://www.jetbrains.com/rider/)IDE 
![image](https://user-images.githubusercontent.com/31106432/218307244-91b53a3a-0e8c-4cf6-bfb6-3873723fd27a.png)

Detail : https://youtrack.jetbrains.com/issue/RSRP-489506/Cannot-convert-expression-type-lambda-expression-to-target-type-System.Linq.Expressions.LambdaExpression-error-is-shown.

**Comment by NeVeSpl** [comment]
It is quite exotic but fully valid C# code, It would be very hard or impossible to replace it with something else. It is a pity that Rider cannot deal with it, but this is a Rider problem, not RDBE.
