### ISSUE TITLE
Show buttons names

### ISSUE THREAD

**Issue by nodatasheet** [NeVeSpl/RevitDBExplorer#11]
Hi guys,

great app, I appreciate what you are doing! 

May I have a humble request:
is it possible to add the names to buttons or (and?) make the button's description tooltip appear faster?
![image](https://user-images.githubusercontent.com/92411255/218728873-32d9e0bd-9112-42f3-83aa-781329affc50.png)

For new users icons are not descriptive enough and currently have to hover over each of them one by one until remember what it actually does.

Thanks in advance!

**Comment by NeVeSpl** [comment]
Button names will be visible only when RDBE window is wider than 919px.

The change is ready, and will be released with v1.4.0
