### ISSUE TITLE
Configs / Info button

### ISSUE THREAD

**Issue by nodatasheet** [NeVeSpl/RevitDBExplorer#12]
Me again 😄 

Please consider adding button for info (aka question mark) and configs (aka gear)... or 2 in 1.

IMHO current right-click way is not obvious for new users and I personally only realized there are configs after seeing them in one of the description gifs

**Comment by NeVeSpl** [comment]
It means that gifs do their job well :D, 

But indeed, for good UX better is to have things visible.

Button was added, and it will be released in 1.4.0.
