### ISSUE TITLE
Failed to initalize Addin

### ISSUE THREAD

**Issue by thumDer** [NeVeSpl/RevitDBExplorer#13]
One of my colleagues was unable to use the addin, it throws the following error both with `v1.4.0` and `v1.3.0` in Revit 2022
![kép](https://user-images.githubusercontent.com/54556708/220562304-49d58079-d547-47f2-8f58-a3dd91d7e9c9.png)

**Comment by NeVeSpl** [comment]
What language version of Revit 2022 UI is used? The error occurs during caching available categories in Revit, and apparently, the name of one of them is causing this problem.

**Comment by thumDer** [comment]
It is the default english

**Comment by thumDer** [comment]
It's US English. I will try to check on his PC about the available categories, there might be some funky named dwg's in the project, because they have their own categories named after their filenames.

**Comment by NeVeSpl** [comment]
That will not be category from project, this caching is done right after addin is loaded, and before any project is loaded.

**Comment by NeVeSpl** [comment]
There is a chance that version 1.5.0 will work, or at least will not crash :D.

**Comment by thumDer** [comment]
Thanks, we'll give it a try! :) 🎉
