### ISSUE TITLE
Issue with latest Revit Lookup install and RDBE

### ISSUE THREAD

**Issue by jmcouffin** [NeVeSpl/RevitDBExplorer#15]
With both installed in revit, I am getting loads of crashes, slowness
https://github.com/jeremytammik/RevitLookup/issues/154#issuecomment-1499091998

**Comment by NeVeSpl** [comment]
I saw that, it is interesting that some interaction exists between RDBE and RL, but I would rather not suspect that dll versioning is a reason for this problem.

Did you have enabled event monitor in RDBE? Event monitor in RDBE when enabled works all the time in the background, which is quite contrary to the event monitor in RL which only works when RL window is displayed.

**Comment by jmcouffin** [comment]
No, not at the time
I tried it just now and I get this when I use the update button 
![image](https://user-images.githubusercontent.com/7872003/230431769-5f12248f-41a9-4959-b93b-7cce87deddcb.png)

**Comment by jmcouffin** [comment]
The crash are hard to identify. 
this time I activated RVTLookup alone, and everything was fine, then RDBE, used the RDBE event monitor, then the Revit lookup one at the same time. No issue except for the update button

**Comment by jmcouffin** [comment]
Now, I closed RDBE and Revit lookup, delete something in my model > Crash

**Comment by NeVeSpl** [comment]
You have done Reload on events? Yes, that produces NullReferenceException from your screen, but this is not related to the problem with RL, this is a separate bug.

**Comment by jmcouffin** [comment]
> You have done Reload on events? Yes, that produces NullReferenceException from your screen, but this is not related to the problem with RL, this is a separate bug.

indeed
