### ISSUE TITLE
Feature Request : A button print snoop data 

### ISSUE THREAD

**Issue by chuongmep** [NeVeSpl/RevitDBExplorer#16]
I just want to discuss this feature, Can we have a button to allow print this data to PDF ? 
![image](https://github.com/NeVeSpl/RevitDBExplorer/assets/31106432/a700d88b-859d-4930-8e26-65c40bfc3f70)

**Comment by NeVeSpl** [comment]
Sure, especially if it would use QuestPDF for PDF generation.

We could add that option to the list view context menu, since I do not expect it will be very popular among the users.

**Comment by nodatasheet** [comment]
Hi guys,

Maybe not pdf, but some other format? 
e.g. html and to open / print in browser?

**Comment by NeVeSpl** [comment]
Why do you need to print that data anyway?

**Comment by nodatasheet** [comment]
Good question 😄 

Sometimes I want to compare some data deeply in child windows. It can be two objects or same object but in different states.
Having too many open windows is inconvenient.
I make screenshot of data, close all windows, open needed window for another one object and compare with screenshot.

Printing to pdf would not be much faster and convenient to me. But opening it in browser for example would be nice.

**Comment by nodatasheet** [comment]
Btw, having tabs for same session instead of multiple windows would be more convenient to me. But that's just my personal preference.

**Comment by NeVeSpl** [comment]
I have comparing/tracking elements/parameters feature on my to-do list, so maybe someday will not be necessary to do manually printscreens.

**Comment by chuongmep** [comment]
I agree that, actually when we export to PDF or HTML, finally we want to look focus on compare element
