### ISSUE TITLE
AppSettings problem in Revit 2024

### ISSUE THREAD

**Issue by ricaun** [NeVeSpl/RevitDBExplorer#17]
I have some problem to disable the `AddRDBECmdToModifyTab` in Revit 2024, for some reason does not work.

And found really annoying that I need to disable it in each Revit version, maybe makes sense to create a unique setting for all versions and store it in some place on the computer. (Like the `FavoriteQueries.json` is saved.)

PS: other configuration in the `AppSettings` does not save as well.
PS2: `ModifyTab` is not removed after change the configuration, need to restart Revit

**Comment by NeVeSpl** [comment]
I know the reason, AppSettings are simply not saved after showing config window: 
https://github.com/NeVeSpl/RevitDBExplorer/blob/791c4c0aa0058682392aa0c729121ac9e90e5499/sources/RevitDBExplorer/MainWindow.xaml.cs#L406

right now, only resizing the window is causing AppSettings to save:

https://github.com/NeVeSpl/RevitDBExplorer/blob/791c4c0aa0058682392aa0c729121ac9e90e5499/sources/RevitDBExplorer/MainWindow.xaml.cs#L400

obviously, it is not how this supposed to work.



> PS2: ModifyTab is not removed after change the configuration, need to restart Revit

That is the intended behaviour, I do not see any usefulness in changing that during Revit session.

**Comment by ricaun** [comment]
> That is the intended behaviour, I do not see any usefulness in changing that during Revit session.

So the user doesn't need to close Revit and open it again to remove an unwanted panel in the `ModifyTab`, if each plugin adds a panel in the `ModifyTab` gonna be a mess... In my opinion, this `ModifyTab` feature should be disabled by default, if that is the case you gonna see how annoying that is to add the RDBE command to the Revit Modify tab.

The configuration does not explain to the user need to reset Revit.

**Comment by NeVeSpl** [comment]
> So the user doesn't need to close Revit and open it again to remove an unwanted panel in the ModifyTab

But this is a one-time only effort/decision, if you hate it - you will disable it forever, if you love it - you will keep it, but no one will be switching it on/off during a single Revit session ....

> The configuration does not explain to the user need to reset Revit.

Indeed it would be nice if the configuration would do that.

**Comment by ricaun** [comment]
I gonna create a PR.

https://github.com/NeVeSpl/RevitDBExplorer/assets/12437519/3ef4d2f6-50d5-4deb-aeec-bd426d99bc84

**Comment by nonghaivinh** [comment]
I can't set  parameters on the latest version, can someone fix it?

![Image](https://github.com/user-attachments/assets/7fd60ea8-9444-46f8-87a9-6f94efce40cd)

**Comment by NeVeSpl** [comment]
The problem is in your script, you have not selected any inputs for the script ....

**Comment by nonghaivinh** [comment]
> The problem is in your script, you have not selected any inputs for the script ....

Where can I see instructions for selecting input, I'm under the impression that when I query it means I've selected it

**Comment by NeVeSpl** [comment]
> > The problem is in your script, you have not selected any inputs for the script ....
> 
> Where can I see instructions for selecting input, I'm under the impression that when I query it means I've selected it

https://github.com/NeVeSpl/RevitDBExplorer/raw/main/documentation/examples/2.0.revit-database-scripting-update-command.gif

**Comment by nonghaivinh** [comment]
> > > The problem is in your script, you have not selected any inputs for the script ....
> > 
> > 
> > Where can I see instructions for selecting input, I'm under the impression that when I query it means I've selected it
> 
> https://github.com/NeVeSpl/RevitDBExplorer/raw/main/documentation/examples/2.0.revit-database-scripting-update-command.gif

yes i tried it and it worked. thanks
