### ISSUE TITLE
Request to allow open class Snoop to use from another application 

### ISSUE THREAD

**Issue by chuongmep** [NeVeSpl/RevitDBExplorer#19]
Hi @NeVeSpl 
I have a problem, need discussion.
I'm working on a package and call action snoop element from your application. At the moment, it can wok fine with element in current document with that way, but can't execute with link element. So can we have any chance to allow open a class and call API for snoop and execute support? 

https://github.com/chuongmep/OpenMEP/blob/722010ef7d0d8665d798e442dac8c3df49ad9166/OpenMEPRevit/Application/Database.cs#L28-L36

**Comment by NeVeSpl** [comment]
What do you think about that looking interface for API, will that be sufficient?
https://github.com/NeVeSpl/RevitDBExplorer/blob/faddbfa61b87df83994f3f7de31f9ba27ca0d1dd/sources/RevitDBExplorer.API.Demo/RunDemoCommand.cs#L37-L38

**Comment by chuongmep** [comment]
Hi @NeVeSpl , it look good for me. I can easier to snoop element or element insider link document.

**Comment by NeVeSpl** [comment]
Nuget that enables communication with RDBE is available here:
https://www.nuget.org/packages/RevitDBExplorer.API

It will be future-compatible, but not backwards-compatible. It means that 1.7 version of API will work with >= 1.7 version of RDBE. That way if nothing changes in API, it will not be necessary to update the API nuget, and it will work out of the box with the new versions of RDBE. 
API is not strongly typed which allows to use single version of nuget for all Revit versions.
