### ISSUE TITLE
System.lO.FileNotFoundException:

### ISSUE THREAD

**Issue by 5616760** [NeVeSpl/RevitDBExplorer#24]
有人遇到这个问题吗？一点生成代码就这样：System.lO.FileNotFoundException:
未能加载文件或程序集'System.Runtime.CompilerServices.Unsafe,
Version=4.0.4.1, Culture=neutral, PublicKeyToken= b03f5f7f11d50a3a
"或它的某一 个依赖项。系统找不到指定的文件。

**Comment by NeVeSpl** [comment]
What version of Revit are you using? And when does this exception occur?

**Comment by 5616760** [comment]
revit 2021，
![image](https://github.com/NeVeSpl/RevitDBExplorer/assets/29964228/c9ee810d-62f3-427a-8a3c-ae0003dfaba0)
![image](https://github.com/NeVeSpl/RevitDBExplorer/assets/29964228/b3654818-1a24-46d9-b645-69b86ecc3444)

**Comment by NeVeSpl** [comment]
So it looks like there is some incompatibility between some of System.Text.Json dependencies and some of the dependencies of Revit. 
 
I am pretty sure that I have made it work in the past, it is interesting that this problem has come back.

As a quick workaround, you can edit `Revit.exe.config` file which is placed right next to `Revit.exe` and add to it:

```
<dependentAssembly>
    <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
</dependentAssembly>
```
