### ISSUE TITLE
No icon on Quick Access Toolbar

### ISSUE THREAD

**Issue by infeeeee** [NeVeSpl/RevitDBExplorer#3]
Hello

If I add this super tool to the [Quick Access Toolbar](https://knowledge.autodesk.com/support/revit/getting-started/caas/CloudHelp/cloudhelp/2022/ENU/Revit-GetStarted/files/GUID-762F3BFE-2508-4255-936D-3BDFE45F1885-htm.html) no icon shows up

![kép](https://user-images.githubusercontent.com/1271737/191703264-38391308-4197-410a-b3f6-f73dd42e2fb9.png)

To reproduce: AddIns->Revit DB Explorer->Rightclick ->Add to Quick Access Toolbar

All supported Revit version affected.

**Comment by NeVeSpl** [comment]
Indeed, a small version of the icon is missing.
