### ISSUE TITLE
Bug when use add-in

### ISSUE THREAD

**Issue by chuongmep** [NeVeSpl/RevitDBExplorer#7]
Problem cause when user installed Addin and snoop keep in screen more than 3 minute. After that, Revit will be show message and close.

![Revit_xO9y67lP7Y](https://user-images.githubusercontent.com/31106432/210492037-234708c1-9755-41d1-8455-9c4f1770c3e5.png)

**Comment by NeVeSpl** [comment]
Were you able to reproduce it? I suspect wpf animation "Revit is busy" may cause something like that, but I am not able to reproduce this bug.

**Comment by chuongmep** [comment]
Hi @NeVeSpl , That is step by step I had try reproduce in my computer : 
-  Open Revit 
- Open Project Sample 
- Open RevitDBExplorer Snoop Active View Keep window 
- Open Dynamo Revit 
- New Script 
- Close Dynamo Revit 
- View Error.

**Comment by chuongmep** [comment]
After thoroughly investigating this issue, this is a problem that exists due to another addin, so I will close this post
